palabra = input("escribime una palabra :")
num_int = int(input("introduce un numero entero:"))
num_float = float (input("introduce un numero flotante:"))
num_porro = complex (input("introduce un numero complejo: "))
print("String: ", palabra)
print ("entero: " , num_int )
print("Flotante:", num_float)
print (" Número complejo:", num_porro)
